### ISSUE TITLE
How to run the yarpserver？

### ISSUE THREAD

**Issue by Bugs-Bunny01** [hsp-iit/gazebo-yarp-digit-plugin#30]
hi,how to run the yarpserver?

**Comment by alecive** [comment]
`yarpserver`

[More info here](https://www.yarp.it//v3.5/yarpserver.html)

**Comment by Bugs-Bunny01** [comment]
> `yarpserver`
> 
> [More info here](https://www.yarp.it//v3.5/yarpserver.html)

hi, thanks for the reply.
I have solved the problem of yarpserver, but when running yarpview, it gives an error that there is no package of respective qt5 module. Does yarpview need to be installed separately?
And in the "Left hand mk3 with one sensor
"yarpview --name /medium:i,./build/bin/grasp-example, GraspExample/script.sh all need to be entered in the new terminal?

**Comment by xEnVrE** [comment]
Dear @Bugs-Bunny01,

the maintainer of this repository, @gabrielecaddeo, is on holidays these days. As soon as he is back he will be able to provide support for this issue. 

Thanks

**Comment by gabrielecaddeo** [comment]
Hi @Bugs-Bunny01 , 
sorry for the late reply. 



> hi, thanks for the reply. I have solved the problem of yarpserver, but when running yarpview, it gives an error that there is no package of respective qt5 module. Does yarpview need to be installed separately?

No

> And in the "Left hand mk3 with one sensor "yarpview --name /medium:i,./build/bin/grasp-example, GraspExample/script.sh all need to be entered in the new terminal?

These three commands have to be launched in 3 different terminals

**Comment by Bugs-Bunny01** [comment]
> Hi @Bugs-Bunny01 , sorry for the late reply.
> 
> > hi, thanks for the reply. I have solved the problem of yarpserver, but when running yarpview, it gives an error that there is no package of respective qt5 module. Does yarpview need to be installed separately?
> 
> No
> 
> > And in the "Left hand mk3 with one sensor "yarpview --name /medium:i,./build/bin/grasp-example, GraspExample/script.sh all need to be entered in the new terminal?
> 
> These three commands have to be launched in 3 different terminals
Thanks for the reply.

**Comment by Bugs-Bunny01** [comment]
Thanks for the reply.

**Comment by Bugs-Bunny01** [comment]
Hi,@gabrielecaddeo 
Thanks for the reply.
